[versions]
appPackageName = "com.rizwansayyed.zene"
targetSDK = "34"
minSDK = "24"

#app version start
currentVersionCode = "45"
currentVersionName = "3.1.041"
#app version end



v1 = "1.0.0"
kotlin-version = "1.12.0"
runtime-version = "2.7.0"
activity-compose-version = "1.8.2"
compose-version = "2024.02.00"
compose-ui-util-version = "1.6.1"
junit-version = "4.13.2"
ext-junit-version = "1.1.5"
espresso-version = "3.5.1"
hilt-version = "2.49"
hilt-compose-version = "1.1.0"
coil-compose-version = "2.5.0"
coroutines-version = "1.7.3"
room-version = "2.6.1"
retrofit-version = "2.9.0"
moshi-version = "1.15.0"
browser-version = "1.7.0"
js-evaluator = "v6.0.0"
webkit-version = "1.10.0"
jsoup-version = "1.16.1"
ok-http-version = "4.12.0"
work-manager-version = "2.9.0"
firebase-bom-version = "32.7.2"
fcm-directboot-version = "23.4.1"
paging-version = "3.2.1"
media3-version = "1.2.1"
glide-version = "4.16.0"
glide-transformations-version = "4.3.0"
amplituda-version = "v2.2.2"
amplituda-compose-version = "v1.1.2"
ffmpeg-version = "6.0-2"
ads-version = "22.6.0"
google-id-version = "1.1.0"
credentials-version = "1.3.0-alpha01"


#plugins
plugin-android-app-version = "8.2.2"
plugin-kotlin-android = "1.9.21"
plugin-hilt = "2.49"
plugin-ksp = "1.9.21-1.0.16"
plugin-google-services = "4.4.1"
firebase-crashlytics-services = "2.9.9"
lifecycleProcess = "2.7.0"








[libraries]
#core
kotlin-core = { group = "androidx.core", name = "core-ktx", version.ref = "kotlin-version" }
lifecycle-runtime = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "runtime-version" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose-version" }
lifecycle-process = { group = "androidx.lifecycle", name = "lifecycle-process", version.ref = "lifecycleProcess" }


#compose ui
android-compose = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-version" }
compose-ui-util = { group = "androidx.compose.ui", name = "ui-util", version.ref = "compose-ui-util-version" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
material3 = { group = "androidx.compose.material3", name = "material3" }


#testing
junit = { group = "junit", name = "junit", version.ref = "junit-version" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "ext-junit-version" }
expresso = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-version" }
ui-test = { group = "androidx.compose.ui", name = "ui-test-junit4" }
ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
ui-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }


#hilt/workmanager
hilt = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt-version" }
hilt-android-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt-version" }
hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hilt-compose-version" }
work-manager = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "work-manager-version" }
hilt-work-manager = { group = "androidx.hilt", name = "hilt-work", version.ref = "hilt-compose-version" }
hilt-compiler = { group = "androidx.hilt", name = "hilt-compiler", version.ref = "hilt-compose-version" }


#single-dep
coil = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil-compose-version" }
coil-gif = { group = "io.coil-kt", name = "coil-gif", version.ref = "coil-compose-version" }
datastore = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "v1" }
browser = { group = "androidx.browser", name = "browser", version.ref = "browser-version" }
js-evaluator = { group = "com.github.evgenyneu", name = "js-evaluator-for-android", version.ref = "js-evaluator" }
web = { group = "androidx.webkit", name = "webkit", version.ref = "webkit-version" }
jsoup = { group = "org.jsoup", name = "jsoup", version.ref = "jsoup-version" }
ffmpeg = { group = "com.arthenica", name = "ffmpeg-kit-full", version.ref = "ffmpeg-version" }



#amplituda
amplituda = { group = "com.github.lincollincol", name = "Amplituda", version.ref = "amplituda-version" }
amplituda-compose = { group = "com.github.lincollincol", name = "compose-audiowaveform", version.ref = "amplituda-compose-version" }


#coroutines
coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines-version" }
coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines-version" }


#room
room = { group = "androidx.room", name = "room-ktx", version.ref = "room-version" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room-version" }


#retrofit
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit-version" }
retrofit-moshi = { group = "com.squareup.retrofit2", name = "converter-moshi", version.ref = "retrofit-version" }
retrofit-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit-version" }
retrofit-scalars = { group = "com.squareup.retrofit2", name = "converter-scalars", version.ref = "retrofit-version" }
retrofit-simplexml = { group = "com.squareup.retrofit2", name = "converter-simplexml", version.ref = "retrofit-version" }
moshi-codegen = { group = "com.squareup.moshi", name = "moshi-kotlin-codegen", version.ref = "moshi-version" }
moshi = { group = "com.squareup.moshi", name = "moshi-kotlin", version.ref = "moshi-version" }


#okhttp
okttp-bom = { group = "com.squareup.okhttp3", name = "okhttp-bom", version.ref = "ok-http-version" }
okttp = { group = "com.squareup.okhttp3", name = "okhttp" }


#firebase
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebase-bom-version" }
firebase-config = { group = "com.google.firebase", name = "firebase-config-ktx" }
firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics-ktx" }
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics-ktx" }
firebase-messaging = { group = "com.google.firebase", name = "firebase-messaging-ktx" }
firebase-messaging-directboot = { group = "com.google.firebase", name = "firebase-messaging-directboot", version.ref = "fcm-directboot-version"  }


#paging
paging-runtime = { group = "androidx.paging", name = "paging-runtime-ktx", version.ref = "paging-version" }



#exoplayer
media3-exoplayer = { group = "androidx.media3", name = "media3-exoplayer", version.ref = "media3-version" }
media3-ui = { group = "androidx.media3", name = "media3-ui", version.ref = "media3-version" }
media3-session = { group = "androidx.media3", name = "media3-session", version.ref = "media3-version" }
media3-hls = { group = "androidx.media3", name = "media3-exoplayer-hls", version.ref = "media3-version" }
media3-legacy = { group = "androidx.legacy", name = "legacy-support-v4", version.ref = "v1" }



#glide
glide = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glide-version" }
glide-transformations = { group = "jp.wasabeef", name = "glide-transformations", version.ref = "glide-transformations-version" }


#ads
play-ads = { group = "com.google.android.gms", name = "play-services-ads", version.ref = "ads-version" }
play-services-ads-lite = { group = "com.google.android.gms", name = "play-services-ads-lite", version.ref = "ads-version" }



#credentials
googleid = { group = "com.google.android.libraries.identity.googleid", name = "googleid", version.ref = "google-id-version" }
credentials = { group = "androidx.credentials", name = "credentials", version.ref = "credentials-version" }
credentials-play-services = { group = "androidx.credentials", name = "credentials-play-services-auth", version.ref = "credentials-version" }




[plugins]
android-application = { id = "com.android.application", version.ref = "plugin-android-app-version" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "plugin-kotlin-android" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "plugin-hilt" }
ksp = { id = "com.google.devtools.ksp", version.ref = "plugin-ksp" }
google-services = { id = "com.google.gms.google-services", version.ref = "plugin-google-services" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebase-crashlytics-services" }







